export const TOGGLE_ACTION = "TOGGLE_ACTION";
export const PING_TO_ZERO = "PING_TO_ZERO";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
